/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chatoy;

import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class App {
  public String getGreeting() {
    return "Hello, Chatoy!";
  }

  private static JPanel rootPanel = new JPanel();

  public static void main(String[] args) {
    JFrame frame = new JFrame("Chatoy");
    frame.getContentPane().add(rootPanel);
    rootPanel.setPreferredSize(new Dimension(680, 600));
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setVisible(true);


  }
}
