package democlass.database;

import java.util.Date;

public class Message {
    private String uuid; // Each message has a unique uuid. This uuid is generated by the client.
    private int sender; // The id of the sender of this message.
    private int room; // The id of the room where this message was sent.
    private MessageContent data; // The content of this message.
    private Date sent; // The time when this message was sent
    private boolean modified; // Whether the message has been modified.

    public Message(String uuid, int sender, int room, MessageContent data, Date sent, boolean modified) {
        this.uuid = uuid;
        this.sender = sender;
        this.room = room;
        this.data = data;
        this.sent = sent;
        this.modified = modified;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public int getSender() {
        return sender;
    }

    public void setSender(int sender) {
        this.sender = sender;
    }

    public int getRoom() {
        return room;
    }

    public void setRoom(int room) {
        this.room = room;
    }

    public MessageContent getData() {
        return data;
    }

    public void setData(MessageContent data) {
        this.data = data;
    }

    public Date getSent() {
        return sent;
    }

    public void setSent(Date sent) {
        this.sent = sent;
    }

    public boolean isModified() {
        return modified;
    }

    public void setModified(boolean modified) {
        this.modified = modified;
    }

    @Override
    public String toString() {
        return "Message{" +
                "uuid='" + uuid + '\'' +
                ", sender=" + sender +
                ", room=" + room +
                ", data=" + data +
                ", sent=" + sent +
                ", modified=" + modified +
                '}';
    }
}
